docker-library/drupal

- 8/Dockerfile
Drupal 8 required OPCache module to run.
> Install OPCache required for Drupal 8 (master)

- 7/Dockerfile
- 8/Dockerfile
Drupal uses Composer a lot; especially Drupal 8, and there are a lot of modules, requiring composer, are being back ported to Drupal 7. Composer use PHP zip extension. Otherwise, see https://github.com/docker-library/php/issues/60
> Update Dockerfile to install PHP zip extension

- 8/apache/Dockerfile
- 8/fpm/Dockerfile
Here is why: http://fabianx.drupalgardens.com/blog/why-drupal-8-defaulting-its-testing-php7-and-why-you-should-too
And the current status of PHP 7 Support in D8: 
> Drupal 8 currently has 100% pass on PHP 7
https://www.drupal.org/node/2454439
> Use PHP 7 for Drupal 8 going forward

- 7/apache/Dockerfile
- 7/fpm/Dockerfile
> Improved support for recent PHP versions, including PHP 7
> 
> Drupal core's automated test suite is now fully passing on a variety of environments where there were previously some failures (PHP 5.4, 5.5, 5.6, and 7). We have also fixed several bugs affecting those versions. These PHP versions are officially supported by Drupal 7 and recommended for use where possible.
> 
> Because PHP 7 is the newest release (and not yet used on many production sites) extra care should still be taken with it, and there are some known bugs, especially in contributed modules (see the discussion for more details). However anecdotal evidence from a variety of users suggests that Drupal 7 can be successfully used on PHP 7, both before and after the 7.50 release.
https://www.drupal.org/requirements/php and …
> Switch Drupal 7 PHP version to 7

- 8.1/apache/Dockerfile
- 8.1/fpm/Dockerfile
- 8.2/apache/Dockerfile
- 8.2/fpm/Dockerfile
Drupal 8 uses a slightly different file structure, which is different from Drupal 7. In short, Drupal 8 puts downloaded modules and themes in /modules and /themes instead of /sites/all/modules and /sites/all/themes. Please see more detail at: http://drupal.stackexchange.com/a/84851/52907
Currently, users cannot install modules or themes via Drupal UI, because of the wrong folder ownership. This patch fixes it.
> Fix Drupal 8 default folder permission

- 7/apache/Dockerfile
- 7/fpm/Dockerfile
- 8.1/apache/Dockerfile
- 8.1/fpm/Dockerfile
- 8.2/apache/Dockerfile
- 8.2/fpm/Dockerfile
Drupal itself also links to https downloads and there are even in the HSTS preload lists of some browsers.
So there is no drawback for also securing the downloads in Docker.
> use "https" for communications with "drupal.org"

- .travis.yml
- 7/apache/Dockerfile
- 7/fpm-alpine/Dockerfile
- 7/fpm/Dockerfile
- 8.2/apache/Dockerfile
- 8.2/fpm-alpine/Dockerfile
- 8.2/fpm/Dockerfile
- 8.3-rc/apache/Dockerfile
- 8.3-rc/fpm-alpine/Dockerfile
- 8.3-rc/fpm/Dockerfile
- generate-stackbrew-library.sh
- update.sh
Just adding some awesome alpine support. ^_^
I didn't touch the apache conf given:
https://github.com/docker-library/php/issues/259
I also updated the `update.sh` script but wasn't sure if any changes needed to the `generate-stackbrew-library.sh` file.
Closes #73
> Add alpine fpm variant

- 8.3/fpm-alpine/Dockerfile
I just realized that Alpine was still using PHP7.0 on Drupal 8.3.x while other flavors already using PHP7.1. So, update this image to use PHP7.1. The official Drupal document suggests no problem with 7.1. https://www.drupal.org/docs/7/system-requirements/php and on the other hand, known and future  PHP7.1 compatibility issues with Core or with 3-rd parties will be worked on https://www.drupal.org/project/issues/search?text=&projects=&assigned=&submitted=&project_issue_followers=&status%5B%5D=Open&issue_tags_op=%3D&issue_tags=PHP+7.1
> Use PHP 7.1 on Alpine and be consistent

- 7/fpm-alpine/Dockerfile
- 8.3/fpm-alpine/Dockerfile
- 8.4-rc/fpm-alpine/Dockerfile
Copying the improvement from https://github.com/docker-library/ruby/pull/161.  Should be no discernible change in packages installed, but does make the sub-shell a little easier to understand.
> Adjust scanelf to properly detect runDeps

- .travis.yml
- 8.4/apache/Dockerfile
- 8.4/fpm-alpine/Dockerfile
- 8.4/fpm/Dockerfile
The stable release has arrived: https://www.drupal.org/project/drupal/releases/8.4.0
This also means 8.3.x reached the end of life. I would wait until 8.4.1 release to remove 8.3.x
> Update to D8.4.0 stable release.

- 7/fpm-alpine/Dockerfile
- 7/fpm/Dockerfile
- 8.4/apache/Dockerfile
- 8.4/fpm-alpine/Dockerfile
- 8.4/fpm/Dockerfile
- 8.5-rc/apache/Dockerfile
- 8.5-rc/fpm-alpine/Dockerfile
- 8.5-rc/fpm/Dockerfile
- Dockerfile-alpine.template
- Dockerfile-debian.template
- update.sh
Adds templating to ease new versions and sync between versions.
Fixes #102 by correctly keeping any library linked by any php extension (like https://github.com/docker-library/wordpress/pull/267 and https://github.com/docker-library/php/pull/556).
> Templatize Dockerfiles for easier updating, fix libpng16 getting purged in stretch

- 7/apache/Dockerfile
- 7/fpm-alpine/Dockerfile
- 7/fpm/Dockerfile
- 8.6/apache/Dockerfile
- 8.6/fpm-alpine/Dockerfile
- 8.6/fpm/Dockerfile
- update.sh
Also run update to bump versions and apply new PHP version.
The update.sh change is a temporary fix to get it to work more often; it needs to be updated again to use the "Releases" API described on https://www.drupal.org/drupalorg/docs/api, but it is only xml. :cry:
Fixes #136
> Bump Drupal 7 to PHP 7.1; Fix update.sh so that it can scrape drupal releases again

- .travis.yml
- 7/apache/Dockerfile
- 7/fpm-alpine/Dockerfile
- 7/fpm/Dockerfile
- 8.6/apache/Dockerfile
- 8.6/fpm-alpine/Dockerfile
- 8.6/fpm/Dockerfile
- 8.7/apache/Dockerfile
- 8.7/fpm-alpine/Dockerfile
- 8.7/fpm/Dockerfile
- Dockerfile-alpine.template
- Dockerfile-debian.template
- generate-stackbrew-library.sh
- update.sh
8.7 stable was released, and 8.5 reached EOL on May 1st, 2019, see https://www.drupal.org/core/release-cycle-overview#current-development-cycle
I also upgraded the PHP version to 7.3 for Drupal 8.7, https://www.drupal.org/docs/8/system-requirements/php-requirements , but kept 7.2 for Drupal 8.6
> Add Drupal 8.7 and remove 8.5

- .travis.yml
- 8.8/apache/Dockerfile
- 8.8/fpm-alpine/Dockerfile
- 8.8/fpm/Dockerfile
- generate-stackbrew-library.sh
Like the situation in https://github.com/docker-library/drupal/pull/150#issue-275965410 , 8.8 is released on Dec. 4, 2019, and meanwhile, 8.6.x is reaching it's  EOL.
So it would be nice if we make changes in time.
> Add Drupal 8.8 and remove 8.6

- 7/apache/Dockerfile
- 7/fpm-alpine/Dockerfile
- 7/fpm/Dockerfile
- update.sh
Closes #165
FYI @giraud-d (thanks for the heads up!)
> Update Drupal 7 to PHP 7.3

- 7/apache/Dockerfile
- 7/fpm-alpine/Dockerfile
- 7/fpm/Dockerfile
- 8.8/apache/Dockerfile
- 8.8/fpm-alpine/Dockerfile
- 8.8/fpm/Dockerfile
- 8.9/apache/Dockerfile
- 8.9/fpm-alpine/Dockerfile
- 8.9/fpm/Dockerfile
- Dockerfile-alpine.template
- Dockerfile-debian.template
- update.sh
- Remove 8.7. It is not compatible with php 7.4
- Add 8.9.
- Do not add 9.0.0 because update.sh needs refactor:
https://www.drupal.org/project/drupal/issues/3074993
Related issue: #170
Closes #158
> Update base image to PHP 7.4

- 7/apache-buster/Dockerfile
- 7/fpm-alpine3.12/Dockerfile
- 7/fpm-buster/Dockerfile
- 8.8/apache-buster/Dockerfile
- 8.8/fpm-alpine3.12/Dockerfile
- 8.8/fpm-buster/Dockerfile
- 8.9/apache-buster/Dockerfile
- 8.9/fpm-alpine3.12/Dockerfile
- 8.9/fpm-buster/Dockerfile
- 9.0/apache-buster/Dockerfile
- 9.0/fpm-buster/Dockerfile
- 9.1/apache-buster/Dockerfile
- 9.1/fpm-alpine3.12/Dockerfile
- 9.1/fpm-buster/Dockerfile
- Dockerfile-7-alpine.template
- Dockerfile-7-debian.template
- Dockerfile-alpine.template
- Dockerfile-debian.template
- generate-stackbrew-library.sh
- update.sh
> Add 9.1 release

- 8.9/apache-buster/Dockerfile
- 8.9/fpm-alpine3.12/Dockerfile
- 8.9/fpm-buster/Dockerfile
- 9.0/apache-buster/Dockerfile
- 9.0/fpm-alpine3.12/Dockerfile
- 9.0/fpm-buster/Dockerfile
- 9.1/apache-buster/Dockerfile
- 9.1/fpm-alpine3.12/Dockerfile
- 9.1/fpm-buster/Dockerfile
- Dockerfile-alpine.template
- Dockerfile-debian.template
- update.sh
Drupal 9.1.x uses Composer 2 by default. This patch fixes that.
> Use the correct default composer version for 9.1.x version or above

- 8.9/php7.4/apache-buster/Dockerfile
- 8.9/php7.4/fpm-alpine3.12/Dockerfile
- 8.9/php7.4/fpm-buster/Dockerfile
- 9.0/php7.4/apache-buster/Dockerfile
- 9.0/php7.4/fpm-alpine3.12/Dockerfile
- 9.0/php7.4/fpm-buster/Dockerfile
- 9.1/php7.4/apache-buster/Dockerfile
- 9.1/php7.4/fpm-alpine3.12/Dockerfile
- 9.1/php7.4/fpm-buster/Dockerfile
- 9.1/php8.0/apache-buster/Dockerfile
- 9.1/php8.0/fpm-alpine3.12/Dockerfile
- 9.1/php8.0/fpm-buster/Dockerfile
- versions.json
- versions.sh
Composer only maintains 1.x and 2.x -- with the release of 2.1, 2.0 is "EOL" (https://github.com/docker-library/official-images/pull/10297)
> Pin to less specific Composer versions

- 7/php7.4/fpm-alpine3.13/Dockerfile
- 7/php7.4/fpm-alpine3.14/Dockerfile
- 8.9/php7.4/fpm-alpine3.13/Dockerfile
- 9.1/php7.4/fpm-alpine3.13/Dockerfile
- 9.1/php8.0/fpm-alpine3.13/Dockerfile
- 9.2/php7.4/apache-buster/Dockerfile
- 9.2/php7.4/fpm-alpine3.13/Dockerfile
- 9.2/php7.4/fpm-alpine3.14/Dockerfile
- 9.2/php7.4/fpm-buster/Dockerfile
- 9.2/php8.0/apache-buster/Dockerfile
- 9.2/php8.0/fpm-alpine3.13/Dockerfile
- 9.2/php8.0/fpm-alpine3.14/Dockerfile
- 9.2/php8.0/fpm-buster/Dockerfile
- generate-stackbrew-library.sh
- versions.json
- versions.sh
- https://www.drupal.org/project/drupal/releases/9.2.0
- bump alpine to 3.13 (3.12 is removed from php images)
- add alpine 3.14 for 9.2+
> Drupal 9.1.x will continue to have security support until December 2021
> Drupal 8.9.x security coverage ends in November 2021
Fixes https://github.com/docker-library/drupal/issues/196
> Add 9.2, drop 9.0 (end of life)

- 10.0-rc/php8.1/apache-bullseye/Dockerfile
- 10.0-rc/php8.1/apache-buster/Dockerfile
- 10.0-rc/php8.1/fpm-alpine3.14/Dockerfile
- 10.0-rc/php8.1/fpm-alpine3.15/Dockerfile
- 10.0-rc/php8.1/fpm-bullseye/Dockerfile
- 10.0-rc/php8.1/fpm-buster/Dockerfile
- versions.json
- versions.sh
Update.sh jobs were failing for `10.0.0-alpha2`:
```console
drupal/core 10.0.0-alpha2 requires php >=8.1.0 -> your php version (8.0.16) does not satisfy that requirement
```
They changed the minimum https://www.drupal.org/node/3264830
> Drupal 10 now requires php 8.1

- 7/php8.0/apache-bullseye/Dockerfile
- 7/php8.0/apache-buster/Dockerfile
- 7/php8.0/fpm-alpine3.15/Dockerfile
- 7/php8.0/fpm-alpine3.16/Dockerfile
- 7/php8.0/fpm-bullseye/Dockerfile
- 7/php8.0/fpm-buster/Dockerfile
- versions.json
- versions.sh
Looks like PHP 8.0 support has been available since `7.79` (https://www.drupal.org/docs/7/system-requirements/php-requirements). This will allow users to continue using [Drupal 7](https://www.drupal.org/about/core/policies/core-release-cycles/drupal-7-roadmap-and-release-schedule) after PHP 7.4 goes end of life at the end of 2022.
> Add php8.0 variants to drupal 7

- 10.0/php8.1/apache-bullseye/Dockerfile
- 10.0/php8.1/apache-buster/Dockerfile
- 10.0/php8.1/fpm-alpine3.16/Dockerfile
- 10.0/php8.1/fpm-alpine3.17/Dockerfile
- 10.0/php8.1/fpm-bullseye/Dockerfile
- 10.0/php8.1/fpm-buster/Dockerfile
- 10.0/php8.2/apache-bullseye/Dockerfile
- 10.0/php8.2/apache-buster/Dockerfile
- 10.0/php8.2/fpm-alpine3.16/Dockerfile
- 10.0/php8.2/fpm-alpine3.17/Dockerfile
- 10.0/php8.2/fpm-bullseye/Dockerfile
- 10.0/php8.2/fpm-buster/Dockerfile
- generate-stackbrew-library.sh
- versions.json
Also update `latest` tag and add `10`.
Fixes https://github.com/docker-library/drupal/issues/234
```diff
--- ../official-images/library/drupal	2022-12-16 16:40:57.125390611 -0800
+++ /dev/fd/63	2023-01-03 15:21:54.123478357 -0800
@@ -1,120 +1,120 @@
-# this file is generated via https://github.com/docker-library/drupal/blob/19559d62d44c5b3d7fe69a957e6154da08300fd9/generate-stackbrew-library.sh
+# this file is generated via https://github.com/docker-library/drupal/blob/85787d8d84242e96e9976f68810025444ae0db4c/generate-stackbrew-library.sh
Maintainers: Tianon Gravi <admwiggin@gmail.com> (@tianon),
Joseph Ferguson <yosifkit@gmail.com> (@yosifkit)
GitRepo: https://github.com/docker-library/drupal.git
-Tags: 10.0.0-rc3-php8.2-apache-bullseye, 10.0-rc-php8.2-apache-bullseye, …
```
> Update 10.0 to GA release

- 10.1/php8.1/apache-bookworm/Dockerfile
- 10.1/php8.1/apache-bullseye/Dockerfile
- 10.1/php8.1/fpm-alpine3.18/Dockerfile
- 10.1/php8.1/fpm-alpine3.19/Dockerfile
- 10.1/php8.1/fpm-bookworm/Dockerfile
- 10.1/php8.1/fpm-bullseye/Dockerfile
- 10.1/php8.2/apache-bookworm/Dockerfile
- 10.1/php8.2/apache-bullseye/Dockerfile
- 10.1/php8.2/fpm-alpine3.18/Dockerfile
- 10.1/php8.2/fpm-alpine3.19/Dockerfile
- 10.1/php8.2/fpm-bookworm/Dockerfile
- 10.1/php8.2/fpm-bullseye/Dockerfile
- 10.2/php8.2/apache-bookworm/Dockerfile
- 10.2/php8.2/apache-bullseye/Dockerfile
- 10.2/php8.2/fpm-alpine3.18/Dockerfile
- 10.2/php8.2/fpm-alpine3.19/Dockerfile
- 10.2/php8.2/fpm-bookworm/Dockerfile
- 10.2/php8.2/fpm-bullseye/Dockerfile
- 10.2/php8.3/apache-bookworm/Dockerfile
- 10.2/php8.3/apache-bullseye/Dockerfile
- 10.2/php8.3/fpm-alpine3.18/Dockerfile
- 10.2/php8.3/fpm-alpine3.19/Dockerfile
- 10.2/php8.3/fpm-bookworm/Dockerfile
- 10.2/php8.3/fpm-bullseye/Dockerfile
- Dockerfile.template
Current images fail to build since buildkit doesn't have `/.dockerenv` during build; see [composer source](https://github.com/composer/composer/blob/94fe2945456df51e122a492b8d14ac4b54c1d2ce/src/Composer/Console/Application.php#L217-L218) for its behavior change based in "being in a container".
Abbreviated failure log:
```console
+ composer create-project --no-interaction drupal/recommended-project:10.1.8 ./
...
- Installing composer/installers (v2.2.0): Extracting archive
The "composer/installers" plugin was not loaded as plugins are disabled.
- Installing drupal/core-composer-scaffold (10.1.8): Extracting archive
The "drupal/core-composer-scaffold" plugin was not loaded as plugins are disabled.
- Installing drupal/core-project-message (10.1.8): Extracting archive
The …
```
> Fixes when building with buildkit

- versions.sh
The end result is the same, but the construction is more ergonomic.
See also https://github.com/docker-library/buildpack-deps/pull/165 (and linked)
> Use jq's `IN()` instead of `index()`

- 10.4/php8.4/apache-bookworm/Dockerfile
- 10.4/php8.4/apache-bullseye/Dockerfile
- 10.4/php8.4/fpm-alpine3.20/Dockerfile
- 10.4/php8.4/fpm-alpine3.21/Dockerfile
- 10.4/php8.4/fpm-bookworm/Dockerfile
- 10.4/php8.4/fpm-bullseye/Dockerfile
- 11.1/php8.4/apache-bookworm/Dockerfile
- 11.1/php8.4/apache-bullseye/Dockerfile
- 11.1/php8.4/fpm-alpine3.20/Dockerfile
- 11.1/php8.4/fpm-alpine3.21/Dockerfile
- 11.1/php8.4/fpm-bookworm/Dockerfile
- 11.1/php8.4/fpm-bullseye/Dockerfile
- generate-stackbrew-library.sh
- versions.json
- versions.sh
PHP 8.4 is supported in 10.4 and 11.1 (https://www.drupal.org/docs/getting-started/system-requirements/php-requirements).
Fixes #280
Also drop a few `10.0` references 🙈
> Add php 8.4 variants

- 10.4/php8.3/apache-bookworm/Dockerfile
- 10.4/php8.3/apache-bullseye/Dockerfile
- 10.4/php8.4/apache-bookworm/Dockerfile
- 10.4/php8.4/apache-bullseye/Dockerfile
- 10.5/php8.3/apache-bookworm/Dockerfile
- 10.5/php8.3/apache-bullseye/Dockerfile
- 10.5/php8.4/apache-bookworm/Dockerfile
- 10.5/php8.4/apache-bullseye/Dockerfile
- 11.1/php8.3/apache-bookworm/Dockerfile
- 11.1/php8.3/apache-bullseye/Dockerfile
- 11.1/php8.4/apache-bookworm/Dockerfile
- 11.1/php8.4/apache-bullseye/Dockerfile
- 11.2/php8.3/apache-bookworm/Dockerfile
- 11.2/php8.3/apache-bullseye/Dockerfile
- 11.2/php8.4/apache-bookworm/Dockerfile
- 11.2/php8.4/apache-bullseye/Dockerfile
- Dockerfile.template
This just enables `output_buffering` and only in Apache as recommended by Drupal upstream.
> Drupal now recommends sites enable PHP output buffering by default, if PHP is run as a server module, e.g. with Apache's `mod_php`.
Fixes #256
Related to #270/#271
> Add upstream recommened setting for output_buffering

- Dockerfile.template
Noticed this when doing #289
We could delete `url` and `md5` from `versions.*` but then we'd also have to drop `date` or commits like https://github.com/docker-library/drupal/commit/7eb8d68a4df0cd6315c107f5263fe791ebe31f72 will look odd.
> Drop Drupal 7 bits (non composer install)
