7/Dockerfile

Issue #8: Updated PHP version to 5.6

---

8/Dockerfile

Update for Drupal 8.0.0-beta15 -- https://www.drupal.org/node/2563023

Update Drupal 8 Dockerfile for drupal 8.0.0-beta15 release

---

8/Dockerfile

The release note: https://www.drupal.org/node/2578775

Upgrade D8 to Beta16. The last beta before RC!

---

8/Dockerfile

The release note: https://www.drupal.org/node/2582663

Upgrade D8 to RC1.

---

7/Dockerfile

Release note: https://www.drupal.org/drupal-7.40-release-notes

Upgrade D7 to 7.40

---

8/Dockerfile

Release note: https://www.drupal.org/node/2598668

Upgrade D8 to RC2

---

7/Dockerfile

Release note: https://www.drupal.org/drupal-7.41-release-notes

Upgrade D7 to 7.41

---

8/Dockerfile

Release Note: https://www.drupal.org/node/2608078

Upgrade D8 to RC3.

---

8/Dockerfile

One last RC before GA release
Release note: https://www.drupal.org/node/2614756

Upgrade D8 to RC4

---

8/Dockerfile

Release note: https://www.drupal.org/node/2627402

Upgrade D8 to 8.0.1

---

8/Dockerfile

Release note: https://www.drupal.org/drupal-8.0.3-release-notes

Upgrade to D8.0.3

---

8/apache/Dockerfile
8/fpm/Dockerfile

Release note: https://www.drupal.org/node/2679347

Update to D8.0.5

---

8.1/apache/Dockerfile
8.1/fpm/Dockerfile

Release note: https://www.drupal.org/drupal-8.1.0-beta2

Upgrade to D8.1-beta2

---

8.1/apache/Dockerfile
8.1/fpm/Dockerfile

Release note: https://www.drupal.org/drupal-8.1.0-rc1-release-notes

Upgrade to D8.1-rc1

---

8.1/apache/Dockerfile
8.1/fpm/Dockerfile

Release note: https://www.drupal.org/drupal-8.1.0-release-notes

Upgrade to D8.1

---

8.1/apache/Dockerfile
8.1/fpm/Dockerfile

Release note: https://www.drupal.org/node/2718713

Upgrade to D8.1.1

---

8.1/apache/Dockerfile
8.1/fpm/Dockerfile

Release note: https://www.drupal.org/project/drupal/releases/8.1.2

Upgrade to D8.1.2

---

.travis.yml
8.1/fpm/Dockerfile
8.2/apache/Dockerfile
8.2/fpm/Dockerfile

drupal 8.2.0-beta1 release note: https://www.drupal.org/project/drupal/releases/8.2.0-beta1
drupal 8.1.8 release note: https://www.drupal.org/project/drupal/releases/8.1.8

Start 8.2 branch and updates

---

.travis.yml
8.3/apache/Dockerfile
8.3/fpm-alpine/Dockerfile
8.3/fpm/Dockerfile
generate-stackbrew-library.sh

Drupal 8.3.0 has been released. Release notes: https://www.drupal.org/project/drupal/releases/8.3.0

Update to 8.3.0

---

.travis.yml
8.4-rc/apache/Dockerfile
8.4-rc/fpm-alpine/Dockerfile
8.4-rc/fpm/Dockerfile

The first alpha1 release note: https://www.drupal.org/project/drupal/releases/8.4.0-alpha1

Add 8.4-rc branch

---

.travis.yml
8.6/apache/Dockerfile
8.6/fpm-alpine/Dockerfile
8.6/fpm/Dockerfile

Closes #131 (fixed in Drupal 8.6).

Bump 8.6-rc to full release

---

8.8/apache-buster/Dockerfile
8.8/fpm-alpine3.12/Dockerfile
8.8/fpm-buster/Dockerfile
8.9/apache-buster/Dockerfile
8.9/fpm-alpine3.12/Dockerfile
8.9/fpm-buster/Dockerfile
9.0/apache-buster/Dockerfile
9.0/fpm-alpine3.12/Dockerfile
9.0/fpm-buster/Dockerfile
Dockerfile-alpine.template
Dockerfile-debian.template

Add the composer bin folder to the PATH

---

SECURITY.md

proposed security.md from #202

---

9.3/php7.4/apache-bullseye/Dockerfile
9.3/php7.4/apache-buster/Dockerfile
9.3/php7.4/fpm-alpine3.14/Dockerfile
9.3/php7.4/fpm-alpine3.15/Dockerfile
9.3/php7.4/fpm-bullseye/Dockerfile
9.3/php7.4/fpm-buster/Dockerfile
9.3/php8.0/apache-bullseye/Dockerfile
9.3/php8.0/apache-buster/Dockerfile
9.3/php8.0/fpm-alpine3.14/Dockerfile
9.3/php8.0/fpm-alpine3.15/Dockerfile
9.3/php8.0/fpm-bullseye/Dockerfile
9.3/php8.0/fpm-buster/Dockerfile
versions.json

Add 9.3, drop eol 9.1

---

10.0-rc/php8.0/apache-bullseye/Dockerfile
10.0-rc/php8.0/apache-buster/Dockerfile
10.0-rc/php8.0/fpm-alpine3.14/Dockerfile
10.0-rc/php8.0/fpm-alpine3.15/Dockerfile
10.0-rc/php8.0/fpm-bullseye/Dockerfile
10.0-rc/php8.0/fpm-buster/Dockerfile
generate-stackbrew-library.sh
versions.json
versions.sh

release note: https://www.drupal.org/project/drupal/releases/10.0.0-alpha1

Added Drupal 10

---

10.0-rc/php8.2/apache-bullseye/Dockerfile
10.0-rc/php8.2/apache-buster/Dockerfile
10.0-rc/php8.2/fpm-alpine3.16/Dockerfile
10.0-rc/php8.2/fpm-alpine3.17/Dockerfile
10.0-rc/php8.2/fpm-bullseye/Dockerfile
10.0-rc/php8.2/fpm-buster/Dockerfile
9.5/php8.0/apache-bullseye/Dockerfile
9.5/php8.0/apache-buster/Dockerfile
9.5/php8.0/fpm-alpine3.16/Dockerfile
9.5/php8.0/fpm-bullseye/Dockerfile
9.5/php8.0/fpm-buster/Dockerfile
9.5/php8.1/apache-bullseye/Dockerfile
9.5/php8.1/apache-buster/Dockerfile
9.5/php8.1/fpm-alpine3.16/Dockerfile
9.5/php8.1/fpm-alpine3.17/Dockerfile
9.5/php8.1/fpm-bullseye/Dockerfile
9.5/php8.1/fpm-buster/Dockerfile
generate-stackbrew-library.sh
versions.json
versions.sh

Add 9.5, remove (EOL) 9.3, add (10+) PHP 8.2, update defaults

---

generate-stackbrew-library.sh

```diff
--- ./drupal    2023-06-20 12:59:47.298777483 -0700
+++ /dev/fd/63  2023-06-20 13:00:16.410668757 -0700
@@ -1,25 +1,25 @@
-# this file is generated via https://github.com/docker-library/drupal/blob/85787d8d84242e96e9976f68810025444ae0db4c/generate-stackbrew-library.sh
+# this file is generated via https://github.com/docker-library/drupal/blob/d38c31ac21e616a31f8e00b118d9cff4a06b8776/generate-stackbrew-library.sh
Maintainers: Tianon Gravi <admwiggin@gmail.com> (@tianon),
Joseph Ferguson <yosifkit@gmail.com> (@yosifkit)
GitRepo: https://github.com/docker-library/drupal.git
-Tags: 10.0.9-php8.2-apache-bookworm, 10.0-php8.2-apache-bookworm, 10-php8.2-apache-bookworm, php8.2-apache-bookworm, 10.0.9-apache-bookworm, 10.0-apache-bookworm, 10-apache-bookworm, apache-bookworm
+Tags: …
```

Move default from bullseye to bookworm

---

10.0/php8.1/fpm-alpine3.19/Dockerfile
10.0/php8.2/fpm-alpine3.19/Dockerfile
10.1/php8.1/fpm-alpine3.19/Dockerfile
10.1/php8.2/fpm-alpine3.19/Dockerfile
10.2-rc/php8.2/fpm-alpine3.19/Dockerfile
10.2-rc/php8.3/fpm-alpine3.19/Dockerfile
7/php8.1/fpm-alpine3.19/Dockerfile
7/php8.2/fpm-alpine3.19/Dockerfile
versions.json
versions.sh

We've really gotta figure out a better way to auto-generate the list of supported variants here based on the `php` image so we don't have failing update jobs every time this square wheel turns. :sweat_smile: :sob:

Update to Alpine 3.19

---

10.1/php8.1/apache-bookworm/Dockerfile
10.1/php8.1/apache-bullseye/Dockerfile
10.1/php8.1/fpm-bookworm/Dockerfile
10.1/php8.1/fpm-bullseye/Dockerfile
10.1/php8.2/apache-bookworm/Dockerfile
10.1/php8.2/apache-bullseye/Dockerfile
10.1/php8.2/fpm-bookworm/Dockerfile
10.1/php8.2/fpm-bullseye/Dockerfile
10.2/php8.2/apache-bookworm/Dockerfile
10.2/php8.2/apache-bullseye/Dockerfile
10.2/php8.2/fpm-bookworm/Dockerfile
10.2/php8.2/fpm-bullseye/Dockerfile
10.2/php8.3/apache-bookworm/Dockerfile
10.2/php8.3/apache-bullseye/Dockerfile
10.2/php8.3/fpm-bookworm/Dockerfile
10.2/php8.3/fpm-bullseye/Dockerfile
7/php8.1/apache-bookworm/Dockerfile
7/php8.1/apache-bullseye/Dockerfile
7/php8.1/fpm-bookworm/Dockerfile
7/php8.1/fpm-bullseye/Dockerfile
7/php8.2/apache-bookworm/Dockerfile
7/php8.2/apache-bullseye/Dockerfile
7/php8.2/fpm-bookworm/Dockerfile
7/php8.2/fpm-bullseye/Dockerfile
Dockerfile.template

Fix `dpkg-query --search` to be more specific

---

10.3/php8.2/fpm-alpine3.22/Dockerfile
10.3/php8.3/fpm-alpine3.22/Dockerfile
10.4/php8.3/fpm-alpine3.22/Dockerfile
10.4/php8.4/fpm-alpine3.22/Dockerfile
10.5-rc/php8.3/fpm-alpine3.22/Dockerfile
10.5-rc/php8.4/fpm-alpine3.22/Dockerfile
11.0/php8.3/fpm-alpine3.22/Dockerfile
11.1/php8.3/fpm-alpine3.22/Dockerfile
11.1/php8.4/fpm-alpine3.22/Dockerfile
11.2-rc/php8.3/fpm-alpine3.22/Dockerfile
11.2-rc/php8.4/fpm-alpine3.22/Dockerfile
versions.json
versions.sh

Depends on https://github.com/docker-library/php/pull/1580

Add Alpine 3.22 (remove Alpine 3.20)
